### ISSUE TITLE
Queue Class does not have an easily acessible "queue-time" member variable

### ISSUE THREAD

**Issue by Rubyj** [EdinburghGenomics/pyclarity-lims#18]
In the Queue Class I feel as if the "queue-time" member variable should exist under artifacts just like location does. However, I have to traverse artifacts._elems[0]._children[0].text to get the queue time. Can we make this so something like artifacts[0].queue_time works? Thanks.

**Comment by tcezard** [comment]
It would probably be a new list of tuple or dict like 
```python
[
    (Artifact(), '2017-12-19T15:02:33.050+00:00', (Container(), 'H11')),
    (Artifact(), '2017-12-19T15:02:33.050+00:00', (Container(), 'H12')), 
]
```
or 
```python
[
    {'artifact': Artifact(), 'queue-time': '2017-12-19T15:02:33.050+00:00', 'location': (Container(), 'H11')},
    {'artifact': Artifact(), 'queue-time': '2017-12-19T15:02:33.050+00:00', 'location': (Container(), 'H12')}
]
```
and queue.artifacts would still return the list of artifacts only for backward compatibility.
It is certainly doable.

**Comment by Rubyj** [comment]
something like this would be perfect! Thanks!
