### ISSUE TITLE
Issue with queued artifacts

### ISSUE THREAD

**Issue by Rubyj** [EdinburghGenomics/pyclarity-lims#21]
When I try to create a queue on version 0.4.2 of this package I am receiving an error. The queue object is created successfully, however when artifacts and queued_artifacts are accessed a stack trace is returned. The stack trace reports "ValueError: unconverted data remains: -0500". I have a feeling this is to due to the queue time for my sample being something like "2018-01-09T15:44:48.571-05:00".

Thank you

**Comment by Rubyj** [comment]
After i did a little detective work, it appears that you are doing a split on '+' to remove the timezone in python 2.7. However, in my case the timezone exists with a '-'.

**Comment by tcezard** [comment]
I would really advise you to switch to python3 because I'm actually striping the timezone for python2.7.
Plus I don't usually run python2.7 so I might not catch any of this issues early

**Comment by Rubyj** [comment]
Unfortunately that is not an option on our current server :/ If you allow me to push a branch I could create a merge request for this issue

**Comment by tcezard** [comment]
You can push a branch to you local fork and open a pull request from there

**Comment by tcezard** [comment]
Quick fix would be to replace 
```python
qt = qt.split('+')[0]
```
```python
m = re.match('(.*)[+-]\d{1,2}\d{1,2}$', qt)
if m:
    qt = m.group(1)
```
I could leave the string as is but since it is meant to parse I though I would go all the way and parse the time as well.
I'll have another look at python2.7 parsing of timezone next week unless you submit a PR before that

**Comment by Rubyj** [comment]
Yup, I get where you are coming from, but if it causes issues to parse because of python versions etc. Then I feel like it should be on the user to parse in their own way.  I will put a PR up on my fork today. Also, side note, using dateparser and pytz could potentially get around this issue.

**Comment by Rubyj** [comment]
Yup, I get where you are coming from, but if it causes issues to parse because of python versions etc. Then I feel like it should be on the user to parse in their own way.  I will put a PR up on my fork today. Also, side note, using dateparser and pytz could potentially get around this issue.

**Comment by Rubyj** [comment]
@tcezard can you push out a new version? Thanks!
