### ISSUE TITLE
Lims _get_instances() returns empty array when start_index is set.

### ISSUE THREAD

**Issue by jonathandixon** [EdinburghGenomics/pyclarity-lims#32]
An empty array is always returned when retrieving a list of entities using the `get_*` methods of the`Lims` class. For example:

```
samples = l.get_samples(start_index=500)
# samples == []
```

The problem is in the [_get_instances()](https://github.com/EdinburghGenomics/pyclarity-lims/blob/master/pyclarity_lims/lims.py#L563-L586) method. The response is only parsed when `start_index` is `None`.

**Comment by tcezard** [comment]
Thanks for reporting this. I can confirm that this is happening when `start_index` is provided.
I never used this option myself and am still unclear what the expected behaviour would be:
 - return one page from the `start_index`
or 
 - return all pages from the `start_index`
