### ISSUE TITLE
next_actions only if condition

### ISSUE THREAD

**Issue by dbarrell** [EdinburghGenomics/pyclarity-lims#36]
Hi, 
I'd like to 'Mark protocol as complete' for each sample ONLY IF 'Samples that passed Aggregate_QC...' is true:

![clarity_complete_if_passed_aggregate](https://user-images.githubusercontent.com/3831752/40841477-7f909e82-65a2-11e8-838e-930932626dc9.png)

I can manually mark as complete using something like:

```python
# TODO: this currently doesn't check the status of the QC flags.
step_actions = step.actions
for artifact in step_actions.next_actions:
    actions = artifact['action'] = 'complete'
step.actions.put()
```

However, I'd like the code to emulate the check that is performed when hitting 'Apply' in the screenshot. Is it just a matter of checking the QC flag for each sample or is there functionality in pyclarity-lims to do this in one easy step as one would do in the web interface?

Thanks

Dan

**Comment by tcezard** [comment]
Hi Dan,
I think you should have access to the QC flag in the artifact entity. 
Just be carefull in your code the variable you called `artifact` is a dictionary that contains the `Artifact`.
I would probably do something like that (code is not tested)
```python
step_actions = step.actions
for next_action in step_actions.next_actions:
    if next_action['artifact'].qc_flag == 'PASSED':
        next_action['action'] = 'complete'
    else:
        # probably requeue ? 
step.actions.put()
```
Checkout the [next action](http://pyclarity-lims.readthedocs.io/en/latest/entities.html#pyclarity_lims.entities.StepActions.next_actions) and [qc_flag](http://pyclarity-lims.readthedocs.io/en/latest/entities.html#pyclarity_lims.entities.Artifact.qc_flag) doc

**Comment by dbarrell** [comment]
Thanks, that was just what was needed.
